apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: resourcegroups.azure.platform.example.org
spec:
  compositeTypeRef:
    apiVersion: azure.platform.example.org/v1alpha1
    kind: XResourceGroup
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: resource-group
            base:
              apiVersion: azure.m.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                providerConfigRef:
                  kind: ClusterProviderConfig
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: rg-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.location
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.id
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.name
                toFieldPath: status.name
