apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: azure-resources
spec:
  activate:
    - resourcegroups.azure.m.upbound.io
    - networkmanagers.network.azure.m.upbound.io
    - networkmanageripampools.network.azure.m.upbound.io
    - virtualnetworks.network.azure.m.upbound.io
    - subnets.network.azure.m.upbound.io
    - securitygroups.network.azure.m.upbound.io
    - subnetnetworksecuritygroupassociations.network.azure.m.upbound.io
