---
# yamllint disable rule:line-length
site_name: Azure Crossplane Platform
site_description: >-
  Reference documentation for the Crossplane compositions available in this
  cluster.
site_url: https://docs.demo.liasis.dev/
repo_url: https://github.com/sjovang/azure-crossplane-demo
repo_name: sjovang/azure-crossplane-demo
edit_uri: blob/main/
docs_dir: docs
site_dir: site
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.instant
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs
        - ../..
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  status:
    experimental: Experimental
