---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: azure-postgresql
  description: >-
    An Azure PostgreSQL Flexible Server and database with a password
    supplied by a Kubernetes Secret.
spec:
  type: crossplane-xrd
  lifecycle: experimental
  owner: group:crd-dev
  definition:
    $text: ./xrd.yaml
