---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 1h
  chart:
    spec:
      chart: crossplane
      # "*" tracks the latest stable chart release automatically.
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: crossplane-system
  targetNamespace: crossplane-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
