---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: subnets.azure.platform.example.org
spec:
  compositeTypeRef:
    apiVersion: azure.platform.example.org/v1alpha1
    kind: XSubnet
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: subnet
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: Subnet
              metadata:
                annotations:
                  crossplane.io/external-name: ""
              spec:
                providerConfigRef:
                  kind: ClusterProviderConfig
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: snet-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceGroupRef.name
                toFieldPath: spec.forProvider.resourceGroupName
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: rg-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.virtualNetworkRef.name
                toFieldPath: spec.forProvider.virtualNetworkName
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: vnet-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ipamAllocation.numberOfAllocatedIpAddresses
                toFieldPath: spec.forProvider.ipamPoolPrefixAllocation[0].numberOfAllocatedIpAddresses  # yamllint disable-line rule:line-length
                policy:
                  fromFieldPath: Optional
              - type: FromCompositeFieldPath
                fromFieldPath: spec.ipamAllocation.ipamPoolId
                toFieldPath: spec.forProvider.ipamPoolPrefixAllocation[0].id
                policy:
                  fromFieldPath: Optional
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.id
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.subnetId
          - name: network-security-group
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: SecurityGroup
              metadata:
                annotations:
                  crossplane.io/external-name: ""
              spec:
                providerConfigRef:
                  kind: ClusterProviderConfig
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: nsg-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.location
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceGroupRef.name
                toFieldPath: spec.forProvider.resourceGroupName
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: rg-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags
              - type: FromCompositeFieldPath
                fromFieldPath: spec.securityRules
                toFieldPath: spec.forProvider.securityRule
                policy:
                  fromFieldPath: Optional
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.networkSecurityGroupId
          - name: subnet-nsg-association
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: SubnetNetworkSecurityGroupAssociation
              spec:
                providerConfigRef:
                  kind: ClusterProviderConfig
                  name: default
                forProvider:
                  subnetIdSelector:
                    matchControllerRef: true
                  networkSecurityGroupIdSelector:
                    matchControllerRef: true
