---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kiac-observability
resources:
  - crossplane-state-metrics-service-account.yaml
  - crossplane-state-metrics-cluster-role.yaml
  - crossplane-state-metrics-cluster-role-binding.yaml
  - crossplane-state-metrics-config.yaml
  - crossplane-state-metrics.yaml
  - crossplane-state-metrics-service.yaml
  - grafana-dashboard.yaml
