---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crd-dev
resources:
  - ../_base
  - network.yaml
  - virtualmachines.yaml
  - apps.yaml
patches:
  - target:
      group: azure.platform.example.org
    patch: |-
      - op: add
        path: /spec/location
        value: swedencentral
