---
apiVersion: azure.platform.example.org/v1alpha1
kind: XResourceGroup
metadata:
  name: crd-dev
spec:
  name: crd-dev
  tags:
    description: CRD development in Crossplane
    managed-by: kiac
---
apiVersion: azure.platform.example.org/v1alpha1
kind: XNetworkManager
metadata:
  name: crd-dev
spec:
  name: crd-dev
  subscriptionId: 297651e0-733c-45f9-b295-ad80c68785f1
  resourceGroupRef:
    name: crd-dev
---
apiVersion: azure.platform.example.org/v1alpha1
kind: XNetworkManagerIPAMPool
metadata:
  name: crd-dev
spec:
  name: crd-dev
  networkManagerRef:
    name: crd-dev
  addressPrefixes:
    - 10.42.0.0/16
