---
apiVersion: environments.platform.example.org/v1alpha1
kind: XWebApplication
metadata:
  name: webdemo01
spec:
  name: webdemo01
  image: docker.io/library/nginx:latest
  location: swedencentral
  appSize: small
  databaseSize: small
