---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-observability
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 2m
  prune: true
  path: ./clusters/dev/observability
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-azure-config
    - name: crossplane-compositions