---
apiVersion: environments.platform.example.org/v1alpha1
kind: XWebApplication
metadata:
  name: appadvisor
spec:
  name: appadvisor
  image: ghcr.io/open-webui/open-webui:main
  location: swedencentral
  appSize: small
  databaseSize: small
  port: 8080
  customDomain:
    hostname: appadvisor.demo.liasis.dev
    dnsZone: demo.liasis.dev
    dnsZoneResourceGroup: rg-public-dns
