---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: networkmanagers.azure.platform.example.org
spec:
  compositeTypeRef:
    apiVersion: azure.platform.example.org/v1alpha1
    kind: XNetworkManager
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: networkManager
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: Manager
              spec:
                providerConfigRef:
                  kind: ClusterProviderConfig
                  name: default
                forProvider:
                  scopeAccesses:
                    - Connectivity
                    - SecurityAdmin
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: vnm-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.subscriptionId
                toFieldPath: spec.forProvider.scope.subscriptionIds[0]
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: /subscriptions/%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.location
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceGroupRef.name
                toFieldPath: spec.forProvider.resourceGroupName
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: rg-%s
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.id
