---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resourcegroup
  - networkmanager
  - networkmanager-ipam-pool
  - virtualnetwork
  - virtualmachine
  - appservice
  - containerapp
  - postgresql
