---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: azure-virtualmachine
  description: >-
    A Linux or Windows virtual machine with its network interface,
    attached to an existing virtual network subnet.
spec:
  type: crossplane-xrd
  lifecycle: experimental
  owner: group:crd-dev
  definition:
    $text: ./xrd.yaml
