---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-azure-activation-policy
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 2m
  prune: true
  path: ./clusters/dev/crossplane/activation-policies/azure
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crossplane-azure-provider
