---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: azure-containerapp
  description: >-
    An Azure Container App and its managed Container App Environment.
spec:
  type: crossplane-xrd
  lifecycle: experimental
  owner: group:crd-dev
  definition:
    $text: ./xrd.yaml
